"""empty message

Revision ID: f93b212d8a87
Revises: 
Create Date: 2023-07-09 17:42:20.512710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93b212d8a87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('altsongs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('altsong_title', sa.String(length=150), nullable=True),
    sa.Column('altartist', sa.String(length=150), nullable=True),
    sa.Column('altalbum', sa.String(length=150), nullable=False),
    sa.Column('altyear', sa.String(), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blusongs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('blusong_title', sa.String(length=150), nullable=True),
    sa.Column('bluartist', sa.String(length=150), nullable=True),
    sa.Column('blualbum', sa.String(length=150), nullable=False),
    sa.Column('bluyear', sa.String(), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countrysongs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('countrysong_title', sa.String(length=150), nullable=True),
    sa.Column('countryartist', sa.String(length=150), nullable=True),
    sa.Column('countryalbum', sa.String(length=150), nullable=False),
    sa.Column('countryyear', sa.String(), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hiphopsongs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hiphopsong_title', sa.String(length=150), nullable=True),
    sa.Column('hiphopartist', sa.String(length=150), nullable=True),
    sa.Column('hiphopalbum', sa.String(length=150), nullable=False),
    sa.Column('hiphopyear', sa.String(), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metalsongs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('metalsong_title', sa.String(length=150), nullable=True),
    sa.Column('metalartist', sa.String(length=150), nullable=True),
    sa.Column('metalalbum', sa.String(length=150), nullable=False),
    sa.Column('metalyear', sa.String(), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rnbsongs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rnbsong_title', sa.String(length=150), nullable=True),
    sa.Column('rnbartist', sa.String(length=150), nullable=True),
    sa.Column('rnbalbum', sa.String(length=150), nullable=False),
    sa.Column('rnbyear', sa.String(), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rnbsongs')
    op.drop_table('metalsongs')
    op.drop_table('hiphopsongs')
    op.drop_table('countrysongs')
    op.drop_table('blusongs')
    op.drop_table('altsongs')
    op.drop_table('user')
    # ### end Alembic commands ###
